### ISSUE TITLE
🐛 Initial playback issues after upgrading to 0.5.1

### ISSUE THREAD

**Issue by Simonh2o** [DonutWare/Fladder#172]
### Description

After upgrading from 0.4.4 to 0.5.1 playback is broken (black screen and infinite loading), this only happens on the first initial title you play after launching the app. Simply exiting the title and retrying works everytime.

### Reproduction steps

```bash
1. Launch app
2. Play any title
3. Playback not starting
```

### Screenshots

```bash
https://i.imgur.com/v2RzzZI.png
```

### Logs

```bash

```

### Platform

Windows

### App Version

0.5.1 Build 85

**Comment by mvastum** [comment]
I have the same issue. I believe it has something to do with the sleep state of your hdd. If it's idle it won't start playing right away. I fix this by starting the title I want to play twice with a short delay in between, to give the hdd a couple seconds to spin up. This seems to help reliably, but it is a bit of a nuisance. If the hdd is already up, it starts right away for me.

**Comment by Simonh2o** [comment]
@mvastum Don't think thats relevant at all... It was working fine on the previous version, and is working on the official jellyfin client. Also not using hdds, thanks anyway.

**Comment by bazzadazza72** [comment]
Does this happen on the Fladder mobile app? I haven't come across this issue myself, so maybe there's some funny business going on somewhere.

**Comment by Simonh2o** [comment]
Got around to testing some more, the web app and mobile app works instantly. Guessing there's a bug with my windows pc after upgrading the app, will try to reinstall.

**Comment by bazzadazza72** [comment]
Hmm... that's interesting. Have you tried switching the media backend to LibMDK? If that doesn't fix the issue, your best bet is to stay on 0.4.4 for the time being.

I'll do some debugging on my Windows environment and I'll report back.

**Comment by bazzadazza72** [comment]
> That's interesting. Have you tried switching the media backend to LibMDK?

You should have an option under the Fladder section of the settings to change the backend.

**Comment by bazzadazza72** [comment]
You could also try disabling hardware acceleration as well, see if that changes anything.

**Comment by bazzadazza72** [comment]
> You should have an option under the ~~Fladder~~ Player section of the settings to change the backend.

Edit: It might be in Player instead, I don't have the latest version so I can't see the option.

**Comment by Simonh2o** [comment]
Works when disabling hardware accel.

**Comment by bazzadazza72** [comment]
Oh excellent. I'll do some debugging in the meantime. Keep this issue open for the moment just to keep track.

**Comment by PartyDonut** [comment]
@Simonh2o Can you check if both backends have the same behaviour?

Also when you say infinite loading do you mean that the videoplayer opens and then just keeps buffering?
Small thing you could try is when it keeps buffering (on first load) press the play and pause button to check if it continues then.

**Comment by Simonh2o** [comment]
I'm not sure what you mean exactly by checking the backends of the app? @PartyDonut

When it comes to the infinite loading part, i'm not sure it's buffering at all. In fact, it seems to not interact with anything you do, such as trying to pause, play or skip. It's almost as if it doesn't get all the data it needs to play (video range, duration etc).
[This is what it looks like](https://i.imgur.com/58IjLaB.png)

**Comment by PartyDonut** [comment]
@Simonh2o Fladder has the option to select a different backend. At the moment there is LibMPV and LibMDK.
You can find these in versions > 0.5.x under Settings -> Player -> Advanced -> Videoplayer backend
It's possible that LibMDK supports whatever it is you are trying to play, it would the issue down.

![Image](https://github.com/user-attachments/assets/5d52124f-3f6c-4e15-97de-4fec3c3cefe7)

**Comment by Simonh2o** [comment]
@PartyDonut Changing the video player backend to MDK from the Default MPV does seem to work as well, loads on first try instantly. Disabling hw accel also worked. However i'd prever MPV as the audio and subtitles seem off using MDK.

**Comment by PartyDonut** [comment]
@Simonh2o I think the codec is unsupported for MPV. That would also explain disabling HW accel, and MDK fixing the problem.

Not really a lot I can do about this besides having a option to force transcoding for that particular codec unfortunately. 
Can you provide the codec information for that specific file?

**Comment by Simonh2o** [comment]
@PartyDonut I might be confused here, but it says "Direct" and on version 0.4.4 the file instantly plays on first try (first title on app launch). I've tried multiple different videos, including web compatible mp4 (x264, aac) and i'm not sure it's a codec issue as all types fail on the newer versions of the app. Just to reiterate: The file does work with the MPV backend, it's just that when the app is first launched, I have to play it twice. If the app stays open and i've played previous titles it works smooth.

Video
CodecHEVC
AVCNo
ProfileMain 10
Level120

Audio
CodecEAC3
AVCNo
Layoutstereo

**Comment by PartyDonut** [comment]
@Simonh2o Sorry my bad misread the issue 🤦🏼 . 
Thank you for clearing that up and providing the additional information.

One last thing you could try is disabling "Enable OS Media Controls" in Settings -> Fladder and check if that fixes the problem.

Windows has a separate implementation for media key controls, that's the only thing I can think of at the moment. 

I'm also still unable to reproduce it, If you're able to debug it locally that would be fantastic otherwise the best option is to wait for this issue #180  to get implemented.

**Comment by Simonh2o** [comment]
Disabling OS media controls did not work. So far only disabling hw accel or changing video backend has worked.

**Comment by stanol** [comment]
I have the same problem. I found out that enabling native libass subtitles solves the problem. So in my case the bug is present only if hardware acceleration is enabled but native libass subtitles are disabled.

**Comment by PartyDonut** [comment]
@Simonh2o I've included a small fix in this test build could you try testing it out?

**Comment by PartyDonut** [comment]
@Simonh2o  I've implemented a small fix in this [build](https://github.com/DonutWare/Fladder/actions/runs/12433408941), can you try this out see if it works?

https://file.io/C0kfTcsRkWh6

**Comment by Simonh2o** [comment]
@stanol Same here, it works but the subtitles aren't customizeable then and looks less than ideal..

@PartyDonut Same exact issue on that build.

**Comment by PartyDonut** [comment]
Last thing I can think of, I reverted MediaKit (libmpv) to the version before 0.5.0. This is just for testing however as this version breaks linux playback in some annoying ways.

Based of this [build](https://github.com/DonutWare/Fladder/actions/runs/12443617499)

https://file.io/YvaA2TNTSl7d

If this doesn't work I'm out of ideas unfortunately and could use some debugging help with how to reproduce this issue.

**Comment by bazzadazza72** [comment]
I'll jump in if y'all don't mind. I've been doing some debugging on Windows for #57 and I haven't encountered any of the issues we've seen.
Not the most encouraging news, but something to pitch in.

**Comment by Simonh2o** [comment]
> Last thing I can think of, I reverted MediaKit (libmpv) to the version before 0.5.0. This is just for testing however as this version breaks linux playback in some annoying ways.
> 
> Based of this [build](https://github.com/DonutWare/Fladder/actions/runs/12443617499)
> 
> https://file.io/YvaA2TNTSl7d
> 
> If this doesn't work I'm out of ideas unfortunately and could use some debugging help with how to reproduce this issue.

@PartyDonut On the new build you linked it looks like it's actually loading the video in contrast to before, same issue still tho.

[Last build](https://streamable.com/flxasu)
[v0.5.1 build 85](https://streamable.com/w34sbu)

**Comment by PartyDonut** [comment]
Well it's a good thing the new media player library was not causing the issue 😕.

I added the help wanted label because so far I have not been able to reproduce it. So any help is more then welcome.

**Comment by Simonh2o** [comment]
Don't think this helps at all, but still confused how you were unable to reproduce this. Just setup a clean windows 11 install on a new pc, as well as windows 10 in a vm env, both have the exact same issue. Open app > play anything > infinite loading loop or just bugged > exit playback > play anything > works as normal. Currently using v0.4.4 as it's the last working version (afaik) without this bug.

**Comment by PartyDonut** [comment]
Not really no 😃 

All jokes aside, I personally use the Windows version a lot and I have never seen this issue. I believe you that it happens however there is very little I can do to help if i'm unable to reproduce it.

Some other things you could check.

1. Does it work fine using the jellyfin demo server? https://demo.jellyfin.org/stable/

2. If debugging locally isn't an option you could try to read through the logs in Settings->About->Error logs. Any errors related to mediakit/mpv/mdk would help.

I have had a look at the 0.4.4 code and I can't see a direct reason why it would break playback on the first opening.

Also did a small test on a different Windows 10, works like expected on first opening. This was a fresh install of Fladder.

**Comment by Simonh2o** [comment]
You're right, it does work with the jellyfin demo. The only difference I can tell is that the playback starts a bit slower on the newer versions? Didnt find any related errors in the log either... Perhaps I could share the jellyfin instance? (wouldn't want to do that publicly)

**Comment by PartyDonut** [comment]
> You're right, it does work with the jellyfin demo. The only difference I can tell is that the playback starts a bit slower on the newer versions?

Yeah the slightly slower start is what I mentioned before being the only real change and maybe cause I could think of. Where it visually looks like it's buffering but the play button still starts the video.

> Perhaps I could share the jellyfin instance? (wouldn't want to do that publicly)

Completely understandable not wanting to share it publicly.
If you can setup a test account on your server with a library only containing problematic videos you can send the url and credentials to this [account.](https://www.reddit.com/user/partydonut/)

And I can take a look at reproducing the issue sometime.

**Comment by Simonh2o** [comment]
Sent you a message now.

**Comment by PartyDonut** [comment]
Thanks for providing the credentials to test on your server 👍🏼. 
However I hate to be the bearer of bad news, but your server works perfectly fine for me.

I've tried direct-play, transcoding, enabling/disabling native subtitles tried different player backends. Both on debug builds and production builds. And always closing Fladder before trying again, this all on Windows of course.
Also tried down-grading to 0.4.4 and then upgrading to 0.5.2

Given that the demo jellyfin server does work for you, one option would be to try a fresh server with just a single video? Perhaps even run the server locally on your Windows PC?

**Comment by Simonh2o** [comment]
Thanks, it must be network related then! Tried using the local ip of the server before as I thought perhaps there's something wrong with the reverse proxy, since im accessing it from the same LAN (local pc > external ip > local server), but it turns out to be working when i'm on a different network, or accessing from a different ip (vpn).

**Comment by PartyDonut** [comment]
Good to hear you found the problem 🥳.

Still wondering why it did work for 0.4.4 though. 
If you do find the network problem and it's not too much trouble do keep me posted (in this issue preferable).

Closing this as resolved for now.

**Comment by Simonh2o** [comment]
Can confirm the latest version, v0.6.0, is working fine for me.
